@startuml AD_updateUserType
partition  <b>updateUserType</b> <i>(UUID module_id, String user_phone, UserType user_type)</i> {
    start
    #lightblue:get module object \n from <b>LOCAL DB/CACHE</b>;
    #palegreen: <b>RPC</b> Update User Type >
    note right
    Only ADMIN level users can
    change another user level
    end note
    if() then (ERROR)
        #pink : <b>Exception</b> \n Communication Error;
        stop
    else
        #yellow: <b>RESP</b> Uset Type Updated <
    endif
    :Update User Result]
    :<b>MAP</b> to Use Case Response Object;
    stop
}
@enduml