@startuml CLASS_repository_less
skinparam dpi 300

title Repository Pattern - Class Diagram


interface IRepositorio << Generic >>{
    + findById()
    + findAll()
    + update()
    + save()
}
interface IRepositorioEntidad{
    + getEntidadesParticulares()
}
abstract RepositorioImpl << Generic >>{
}
note left: Empleando ORM
class RepositorioEntidadImpl{
}

IRepositorioEntidad ..|> IRepositorio
RepositorioImpl ..|> IRepositorio
RepositorioEntidadImpl --|> RepositorioImpl
RepositorioEntidadImpl ..|> IRepositorioEntidad
@enduml