@startuml CLASS_command_app

title Command Pattern on PI

skinparam class {
BackgroundColor<<Android>> PaleGreen
ArrowColor<<Android>> SeaGreen
BorderColor<<Android>> SpringGreen
}

interface UseCase {
    +Response execute(Request)
}
class Activity <<Android>>{
    +Repository repo
    +Presenter presenter
}
class Repository{
    +getData()
    +setData()
}
class Presenter{
    +UseCase useCase
}

class UseCaseImpl
Activity *--> Presenter
Presenter *--> UseCase
UseCaseImpl ..|> UseCase
UseCaseImpl *--> Repository
Activity *--> Repository
@enduml