@startuml SD_command_app

skinparam BoxPadding 10
skinparam ParticipantPadding 10

'title Sequence Diagram Command Pattern as Implemented

skinparam participant {
    BackgroundColor<<Android>> PaleGreen
    ArrowColor<<Android>> SeaGreen
    BorderColor<<Android>> SpringGreen
}

box "Implementation" #White
    participant anActivity <<Android>>
    participant aRepository
    participant aUseCase
    participant aPresenter
end box

activate anActivity 
== Initialization ==
create aRepository
anActivity -> aRepository: new Repository() \t\t

create  aUseCase
anActivity -> aUseCase: new UseCase(aRepository)

create aPresenter
anActivity -> aPresenter: new Presenter(aUseCase)

== Operation ==
activate aPresenter
aPresenter -> aUseCase: execute(aRequest)
activate aUseCase
aUseCase -> aRepository: getData(parameters)
activate aRepository
aRepository --> aUseCase
aUseCase --> aPresenter: aResponse
deactivate aUseCase
deactivate aRepository
deactivate aPresenter

@enduml