@startuml SEQ_mdns_dnssd
skinparam dpi 300

!pragma teoz true
hide footbox 
participant "ServiceBrowser \n <b>192.168.0.11</b>" as SB
participant "Router \n <b>224.0.0.251:5353</b>" as R
participant "ServiceAnnouncer \n <b>192.168.0.22</b>" as SA

group #PaleGreen mDNS
    group #LightYellow DNS_SD 
        SB -> R: <b>[PTR] query</b> \n _urbit._http._tcp.local
        & R ->  SA
        SA -> R: <b>[PTR] response</b> \n modulo_001._urbit._http._tcp.local \n service_type = _urbit._http._tcp \n service_instance = modulo_001 \n domain = local
        & R ->  SB

        SB -> R: <b>[SRV] query</b> \n modulo_001._urbit._http._tcp.local
        & R ->  SA
        SA -> R: <b>[SRV] response</b> \n serive_instance =modulo_001._urbit._http._tcp.local \n priority = 0 \n weight = 1 \n port = 1234 \n endpoint = modulo_001.local
        & R ->  SB

        SB -> R: <b>[TXT] query</b> \n modulo_001._urbit._http._tcp.local
        & R ->  SA
        SA -> R: <b>[TXT] response</b> \n service =urbit_porton \n uuid = urbit-12345678 \n version = 0.4
        & R ->  SB

        SB -[hidden]-> R
    end
    SB -> R: <b>[A] query</b> \n modulo_001.local
    & R ->  SA
    SA -> R: <b>[A] response</b> \n 192.168.0.22
    & R ->  SB
    SB -[hidden]-> R
end 