@startuml SEQ_command_def
title Sequence Diagram Command Pattern

participant elCliente
activate elCliente 
== Initialization ==
elCliente -> unReceptor: new Receptor() \t\t\t\t\t
activate unReceptor
elCliente -> unComando: new Comando(unReceptor)
activate unComando
elCliente -> unInvocador: new Invocador(unComando)
activate unInvocador
== Operation ==
unInvocador -> unComando: execute()
unComando -> unReceptor: action()
unReceptor --> unComando
unComando --> unInvocador
deactivate unComando

@enduml